### ISSUE TITLE
uJIT hits assertion at lj_record.c:1453

### ISSUE THREAD

**Issue by neoxic** [iponweb/luavela#30]
uJIT (current master) crashes with assertion  on Centos 7 if built with `CMAKE_BUILD_TYPE=DEBUG`.
```
ujit: /home/master/rpm/luavela-master/src/jit/lj_record.c:1453: rec_varg_setup: Assertion `nvararg >= 0' failed.
```
I guess this assertion goes largely unnoticed in release builds introducing opportunity for more subtle bugs and/or state corruption somewhere down the line.

The code that causes this is rather complex, and we couldn't strip it down to a simple test case. Nevertheless, it works well on vanilla Lua 5.1 and LuaJIT 2.x, and a move to uJIT has been just an experiment for us for some time. The code employs heavy use of coroutines, varargs/results and various tricks using `setfenv()`.

**Comment by neoxic** [comment]
@igelhaus FYI. Please let me know if there's anything we can do to help hunt this bug if anyone interested of course...

**Comment by neoxic** [comment]
```
#0  0x00007f249cb3f387 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
55	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0  0x00007f249cb3f387 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f249cb40a78 in __GI_abort () at abort.c:90
#2  0x00007f249cb381a6 in __assert_fail_base (fmt=0x7f249cc93ce0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x494cc8 "nvararg >= 0",
    file=file@entry=0x493758 "/home/master/rpm/luavela-master/src/jit/lj_record.c", line=line@entry=1453, function=function@entry=0x495230 <__PRETTY_FUNCTION__.8523> "rec_varg_setup") at assert.c:92
#3  0x00007f249cb38252 in __GI___assert_fail (assertion=assertion@entry=0x494cc8 "nvararg >= 0", file=file@entry=0x493758 "/home/master/rpm/luavela-master/src/jit/lj_record.c",
    line=line@entry=1453, function=function@entry=0x495230 <__PRETTY_FUNCTION__.8523> "rec_varg_setup") at assert.c:101
#4  0x000000000043a6f1 in rec_varg_setup (J=0x7f249dc09888, J=0x7f249dc09888, trftsz=318799887, nresults=-1, dst=13) at /usr/src/debug/luavela-master/src/jit/lj_record.c:1453
#5  rec_varg (J=J@entry=0x7f249dc09888, dst=dst@entry=13, nresults=nresults@entry=-1) at /usr/src/debug/luavela-master/src/jit/lj_record.c:1678
#6  0x000000000043d282 in lj_record_ins (J=J@entry=0x7f249dc09888) at /usr/src/debug/luavela-master/src/jit/lj_record.c:2135
#7  0x000000000043522e in trace_state (L=<optimized out>, dummy=<optimized out>, ud=<optimized out>) at /usr/src/debug/luavela-master/src/jit/lj_trace.c:569
#8  0x0000000000471984 in lj_vm_cpcall ()
#9  0x0000000000435b80 in lj_trace_ins (J=<optimized out>, pc=<optimized out>) at /usr/src/debug/luavela-master/src/jit/lj_trace.c:629
#10 0x0000000000475eac in hook_record_ins (pc=0x7f249bb29dc8, L=0x7f249b630db8) at /usr/src/debug/luavela-master/src/uj_hook.c:118
#11 uj_hook_ins (L=0x7f249b630db8, pc=0x7f249bb29dc8) at /usr/src/debug/luavela-master/src/uj_hook.c:177
#12 0x0000000000473cbe in lj_vm_inshook ()
#13 0x0000000000472597 in lj_ff_coroutine_resume ()
#14 0x000000000040a80a in lua_pcall (L=<optimized out>, nargs=<optimized out>, nresults=<optimized out>, errfunc=<optimized out>) at /usr/src/debug/luavela-master/src/uj_capi.c:966
#15 0x0000000000405e4c in docall (L=0x7f249dc09378, narg=1, clear=0) at /usr/src/debug/luavela-master/src/ujit.c:123
#16 0x0000000000406c0a in preprocess_and_call (clear=0, narg=1, L=0x7f249dc09378) at /usr/src/debug/luavela-master/src/ujit.c:222
#17 handle_script (n=<optimized out>, argv=<optimized out>, L=<optimized out>) at /usr/src/debug/luavela-master/src/ujit.c:344
#18 pmain (L=0x7f249dc09378) at /usr/src/debug/luavela-master/src/ujit.c:750
#19 0x0000000000471489 in lj_BC_FUNCC ()
#20 0x000000000040a8d3 in lua_cpcall (L=<optimized out>, func=<optimized out>, ud=<optimized out>) at /usr/src/debug/luavela-master/src/uj_capi.c:989
#21 0x000000000040585d in main (argc=3, argv=0x7ffce98fac48) at /usr/src/debug/luavela-master/src/ujit.c:790
(gdb) fr 4
#4  0x000000000043a6f1 in rec_varg_setup (J=0x7f249dc09888, J=0x7f249dc09888, trftsz=318799887, nresults=-1, dst=13) at /usr/src/debug/luavela-master/src/jit/lj_record.c:1453
1453	  lua_assert(nvararg >= 0);
(gdb) print nvararg
$1 = -1
(gdb)
```

**Comment by igormunkin** [comment]
> Please let me know if there's anything we can do to help hunt down this bug. If anyone interested of course...

@neoxic, does the issue still present? Are there any related updates?

**Comment by neoxic** [comment]
The following fixes to LuaJIT might be related to this issue:

https://github.com/LuaJIT/LuaJIT/issues/611
https://github.com/LuaJIT/LuaJIT/issues/624

**Comment by igormunkin** [comment]
Right, I'll see whether these issues are related to this one, thanks!
